// Generated by CoffeeScript 1.10.0
(function() {
  var messageDiv, messageP;

  messageP = "";

  messageDiv = "";

  $(function() {
    $("#message a").on("click", function() {
      return $("#message").fadeOut(500);
    });
    messageDiv = $("#message");
    return messageP = $("#message p");
  });

  this.showErrorMessage = function(message) {
    messageP.text(message);
    messageDiv.removeClass();
    messageDiv.addClass("alert alert-danger");
    return messageDiv.fadeIn(400);
  };

  this.showMessage = function(message) {
    messageP.text(message);
    messageDiv.removeClass();
    messageDiv.addClass("alert alert-success");
    return messageDiv.fadeIn(400);
  };

  this.hideMessage = function() {
    return messageDiv.fadeOut(400);
  };

}).call(this);
